"""Agrego campos SWAPI a Character

Revision ID: b89f92d8caae
Revises: c06a6935a22a
Create Date: 2025-09-14 19:52:44.985888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89f92d8caae'
down_revision = 'c06a6935a22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=False),
    sa.Column('cost_in_credits', sa.String(length=50), nullable=False),
    sa.Column('length', sa.String(length=50), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=50), nullable=False),
    sa.Column('crew', sa.String(length=50), nullable=False),
    sa.Column('passengers', sa.String(length=50), nullable=False),
    sa.Column('cargo_capacity', sa.String(length=50), nullable=False),
    sa.Column('consumables', sa.String(length=50), nullable=False),
    sa.Column('hyperdrive_rating', sa.String(length=20), nullable=False),
    sa.Column('MGLT', sa.String(length=20), nullable=False),
    sa.Column('starship_class', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_starship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet_film',
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('planet_id', 'film_id')
    )
    op.create_table('starship_film',
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], ),
    sa.PrimaryKeyConstraint('starship_id', 'film_id')
    )
    op.create_table('character_film',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'film_id')
    )
    op.create_table('character_starship',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'starship_id')
    )
    op.create_table('favorite_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite_planets')
    op.drop_table('favorite_characters')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('homeworld_id', sa.Integer(), nullable=False))
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'planet', ['homeworld_id'], ['id'])
        batch_op.drop_column('weight')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('climate', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('surface_water', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('population', sa.String(length=50), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('population')
        batch_op.drop_column('surface_water')
        batch_op.drop_column('terrain')
        batch_op.drop_column('gravity')
        batch_op.drop_column('climate')
        batch_op.drop_column('diameter')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('height',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('homeworld_id')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')

    op.create_table('favorite_characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('favorite_characters_character_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('favorite_characters_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favorite_characters_pkey'))
    )
    op.create_table('favorite_planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name=op.f('favorite_planets_planet_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('favorite_planets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favorite_planets_pkey'))
    )
    op.drop_table('favorite_character')
    op.drop_table('character_starship')
    op.drop_table('character_film')
    op.drop_table('starship_film')
    op.drop_table('planet_film')
    op.drop_table('favorite_starship')
    op.drop_table('favorite_planet')
    op.drop_table('starship')
    op.drop_table('film')
    # ### end Alembic commands ###
